### ISSUE TITLE
Question: get unmasked text

### ISSUE THREAD

**Issue by alanbre** [LeandroNovak/extended_masked_text#13]
Is there any way to get unmasked text from the controller?

**Comment by fasunna** [comment]
@alanbre  From MoneyMaskController there is a numberValue method to retrieve the value. The MaskedTextController there is a private _removeMask. @LeandroNovak I think it would be nice to export a public method for unmask using the _removeMask.

**Comment by LeandroNovak** [comment]
Sure, I will add a new field with the unmasked text

**Comment by alangodoi** [comment]
Is there a way to get unmasked text while this feature isn't released?

**Comment by LeandroNovak** [comment]
Feature added, please check the lasted release.
