### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by marcio-ota** [LeandroNovak/extended_masked_text#14]
Uso para fazer a mascara de CPF, como o exemplo, mas nestas ultimas versoes, com o cursor, parou de funcionar.
Cada vez que chega no proximo digito apos o . ele volta o cursor uma casa.
Tem alguma forma de desativar esse cursor? Em dispositivos moveis parece sem sentido...

obrigado...

Flutter: 2.2.0, sdk 2.13.0, iphone simulator 14.5

**Comment by LeandroNovak** [comment]
Estou tentando resolver problemas relacionados ao cursor. O problema acontece mesmo passando `CursorBehavior.end`?

**Comment by fasunna** [comment]
É possível adicionar uma condição para desabilitar esse comportamento do cursor no código, talvez seria o melhor caminho até conseguir uma solução mais robusta. O que acha @LeandroNovak ?

Entretanto, em tanto mobile quanto desktop vejo como uma funcionalidade necessária, e o fato de editar o meio o cursor pular para o final deixa muitos usuários incomodados com um app assim.

@marcio-ota confirme a versão que está utilizando do pacote fazendo o favor.

**Comment by marcio-ota** [comment]
@LeandroNovak com o CursorBehavior.end funcionou como antes! obrigado!

@fabricio-godoi versão 2.2.1

**Comment by fasunna** [comment]
@marcio-ota 

Acabei de submeter um novo PR para o problema do cursor. Se puder realizar alguns testes no iOS seria ótimo!

 [Pull Request](https://github.com/LeandroNovak/extended_masked_text/pull/18)

Há diferenças entre Flutter 2.0.0  e Flutter 2.2.0/2.2.1, por isso pode haver alguma pequena diferença entre ambos.

Foquei as correções para as versões mais novas, mas tentando manter suporte para a antiga.

@LeandroNovak acho que poderia fechar essa issue, sendo que é uma variante dessa outra https://github.com/LeandroNovak/extended_masked_text/issues/9, o que acha?

Obrigado pessoal!

**Comment by LeandroNovak** [comment]
Related to #18
