### ISSUE TITLE
Remove print on listener

### ISSUE THREAD

**Issue by guigzp** [LeandroNovak/extended_masked_text#20]
First of all, great lib and thank you for the maintenance. 

If you could remove the print in the listener would be great, it's a really minor thing but annoying when debugging.

![image](https://user-images.githubusercontent.com/33470622/129947562-dba6883e-76d0-47fb-9ceb-49a4da583a58.png)

**Comment by LeandroNovak** [comment]
Fixed it yesterday (08/19/2021) within version 2.3.1
