### ISSUE TITLE
Whenever mask is applied cursor goes to the end

### ISSUE THREAD

**Issue by klausgreiner** [LeandroNovak/extended_masked_text#3]
There's much to say.
for example R$ 555,55
setting the cursor R$ 55(here)5,55 and type another 5 would moe the cursor to the end.
IMO shud stay in the same place.

**Comment by LeandroNovak** [comment]
Thanks for the report, I will start working on this issue as soon as I can.

**Comment by klausgreiner** [comment]
I might have to solve this issue today. So if I come up with the solution i'll send you the solution/or submit a  PR.
Update: I decided to use a formatter instead it solved my issue without the weird problems that were happening.

**Comment by LeandroNovak** [comment]
This should be fixed in the version 1.1.0
