### ISSUE TITLE
afterChange and beforeChange listeners

### ISSUE THREAD

**Issue by vitorhm** [LeandroNovak/extended_masked_text#4]
The original no longer supported library have a **afterChange** and **beforeChange** listener:
`Function afterChange = (String previous, String next) {};`
`Function beforeChange = (String previous, String next) {
    return true;
  };`

Can we have this here?

**Comment by LeandroNovak** [comment]
Sure, I will add this feature and publish a new version

**Comment by vitorhm** [comment]
Thank you, just let me know if you need some help

**Comment by LeandroNovak** [comment]
Can you confirm if the latest version works as expected? 
This is the commit in which I've made the changes: 295371c

**Comment by vitorhm** [comment]
Yes, I'll test now and let you know, thank you

**Comment by vitorhm** [comment]
All working as expected, thank you for making this change!
